### ISSUE TITLE
Heroicons not supported

### ISSUE THREAD

**Issue by makroxyz** [lara-zeus/delia#14]
Filament v4 I have a resource with 

```php
protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedCpuChip;
```

then in a view page I added ```BookmarkHeaderAction```

this is the error:
```
LaraZeus\Delia\Delia::toggle(): Argument #3 ($icon) must be of type string, Filament\Support\Icons\Heroicon given, called in /var/www/html/vendor/lara-zeus/delia/src/Filament/Actions/HasDefaultAttributes.php on line 
```

**Comment by atmonshi** [comment]
sorry for the delay, fixed with the last version
and will get to your email soon :)

**Comment by makroxyz** [comment]
Still not working, error on adding bookmark:

LaraZeus\Delia\Delia::toggle(): Argument #3 ($icon) must be of type string, Filament\Support\Icons\Heroicon given, called in /var/www/html/vendor/lara-zeus/delia/src/Filament/Actions/HasDefaultAttributes.php on line 41

**Comment by atmonshi** [comment]
sorry I had a wrong release, can you update now and check
